import type { VoxelPalette } from "../../types";

export const palette: VoxelPalette = {
  air: { color: "#000000" },
  grass: { color: "#00ff00" },
  stone: { color: "#808080" },
  dirt: { color: "#964B00" },
  water: { color: "#4fa4b8" },
  wood: { color: "#6d4c41" },
  leaves: { color: "#4caf50" },
  sand: { color: "#fdd835" },
  brick: { color: "#b71c1c" },
  roof: { color: "#5d4037" },
  glass: { color: "#81d4fa" },
  plank: { color: "#ffcc80" },
  concrete: { color: "#9e9e9e" },
  asphalt: { color: "#424242" },
  road_white: { color: "#eeeeee" },
  road_yellow: { color: "#ffeb3b" },
  neon_blue: { color: "#00e5ff" },
  neon_pink: { color: "#f50057" },
  metal: { color: "#607d8b" },
  snow: { color: "#ffffff" },
  lava: { color: "#ff5722" },
};
